apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${IMAGE_NAME}-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${IMAGE_NAME}
    spec:
      containers:
      - name: ${IMAGE_NAME}
        image: "${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${GITHUB_SHA}"
        ports:
        - containerPort: 3000
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef: 
              name: ${IMAGE_NAME}-secret
              key: MY_SECCRET
        resources:
          limits: 
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"