apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}-service
  namespace: production
spec:
  selector:
    app: ${IMAGE_NAME}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer