apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}-service
  namespace: production
spec:
  selector:
    app.kubernetes.io/name: ${IMAGE_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080