name: CI build and test
on:
    pull_request:
        branches:
            - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SetUp NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 15.5.1
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: NPM install
      run: npm ci
      working-directory: ./app
    
    - name: RUN ESLint
      run: npm run lint
      working-directory: ./app

    - name: RUN Prettier
      run: npm run prettier
      working-directory: ./app

    - name: RUN unit tests
      run: npm run test
      working-directory: ./app

    - name: Build app
      run: npm run build
      working-directory: ./app