name: Deploy to EKS
on:
    push:
        branches:
            - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t ${{ vars.IMAGE_NAME }}:${{ github.sha }} ./app

    - name: Login into Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Push the Docker image
      run: |
        docker tag ${{ vars.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        echo "KUBECONFIG_FILE" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        envsubst < k8s/secret.yml > secret.yml && kubectl replace --force -f secret.yml || kubectl apply -f secret.yml
        envsubst < k8s/deployment.yml > deployment.yml && kubectl apply -f deployment.yml
        envsubst < k8s/service.yml > service.yml && kubectl apply -f service.yml
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
        IMAGE_NAME: ${{ vars.IMAGE_NAME }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        SECRET: ${{ secrets.K8S_SECRET }}
